spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
#  jpa:
#    # Provide database platform that is being used
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      # New database is created when app starts and destroyed when app stops
#      ddl-auto: update
#    # Show sql when spring data jpa performs query
#    show-sql: false
#    properties:
#      hibernate:
#        # Format queries
#        format_sql: true
  datasource:
#    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
#    username: ${POSTGRES_USER:postgres}
#    password: ${POSTGRES_PASSWORD:password}
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-doc: backend-service
    server: http://localhost:${server.port}
    title: Fasep API Document
    version: 1.0.0
