server:
  port: 8080

spring:
  application:
    name: backend-service
  profiles:
    active: @spring.profiles.active@

management: # health check
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: OFF